ekf_filter_node:
  ros__parameters:

    use_sim_time: true
    frequency: 30.0

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

   #odom
    odom0: /diff_cont/odom
    odom0_config: [
      true,  true,  false,    # x, y, z
      false, false, true,     # roll pitch yaw
      false, false, true,     # vx vy vz
      false, false, false, 
      false, false, false
    ]
    odom0_differential: false

    #imu
    imu0: /imu/data
    imu0_config: [
      false, false, false,      # position
      true,  true,  true,       # orientation
      false, false, true,       # angular velocity
      false, false, false,      # linear velocity
      true,  true,  true        # linear acceleration
    ]

    imu0_remove_gravitational_acceleration: true
